{
 "title": "AirGradient Air Quality",
 "description": "AirGradient Grafana",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_temperature_celsius"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airgradient_humidity_percent" }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airgradient_co2_ppm" }
   ]
  },
  {
   "title": "TVOC",
   "type": "stat",
   "description": "Sensirion VOC Index (unitless). Lower is better. Indicates relative indoor air quality trends, not absolute concentration.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airgradient_tvoc_index" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "airgradient_temperature_compensated_celsius"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "airgradient_humidity_compensated_percent"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "airgradient_co2_ppm" }
   ]
  },
  {
   "title": "Total Volatile Organic Compounds (TVOC)",
   "type": "timeseries",
   "description": "Sensirion VOC Index (unitless). Lower is better. Indicates relative indoor air quality trends, not absolute concentration.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "airgradient_tvoc_index" }
   ]
  },
  {
   "title": "Particle Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "conmgdL" } },
   "targets": [
    {
     "expr": "airgradient_pm003_count_pdl",
     "legendFormat": "Particle count 0.3um per dL (only for indoor monitor)"
    },
    {
     "expr": "airgradient_pm005_count_pdl",
     "legendFormat": "Particle count 0.5um per dL (only for indoor monitor)"
    },
    {
     "expr": "airgradient_pm01_count_pdl",
     "legendFormat": "Particle count 1um per dL (only for indoor monitor)"
    },
    {
     "expr": "airgradient_pm02_count_pdl",
     "legendFormat": "Particle count 2um per dL (only for indoor monitor)"
    },
    {
     "expr": "airgradient_pm10_count_pdl",
     "legendFormat": "Particle count 10um per dL (only for indoor monitor)"
    },
    {
     "expr": "airgradient_pm50_count_pdl",
     "legendFormat": "Particle count 50um per dL (only for indoor monitor)"
    }
   ]
  },
  {
   "title": "PM1.0 in ug/m3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "airgradient_pm01_ugm3",
     "legendFormat": "PM1.0 in ug/m3 (atmospheric environment)"
    },
    {
     "expr": "airgradient_pm01_standard_ugm3",
     "legendFormat": "PM1.0 in ug/m3 (standard particle)"
    }
   ]
  },
  {
   "title": "Senisiron VOC Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "avg_over_time(airgradient_tvoc_index[5m])",
     "legendFormat": "Senisiron VOC Index"
    }
   ]
  },
  {
   "title": "PM2.5 in ug/m3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "airgradient_pm02_ugm3",
     "legendFormat": "PM2.5 in ug/m3 (atmospheric environment)"
    },
    {
     "expr": "airgradient_pm02_compensated_ugm3",
     "legendFormat": "PM2.5 in ug/m3 with correction applied (from fw version 3.1.4 onwards)"
    },
    {
     "expr": "airgradient_pm02_standard_ugm3",
     "legendFormat": "PM2.5 in ug/m3 (standard particle)"
    }
   ]
  },
  {
   "title": "Senisirion NOx Index",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "avg_over_time(airgradient_nox_index[5m])",
     "legendFormat": "Senisirion NOx Index"
    }
   ]
  },
  {
   "title": "PM10 in ug/m3",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "airgradient_pm10_ugm3",
     "legendFormat": "PM10 in ug/m3 (atmospheric environment)"
    },
    {
     "expr": "airgradient_pm10_standard_ugm3",
     "legendFormat": "PM10 in ug/m3 (standard particle)"
    }
   ]
  },
  {
   "title": "NOx Raw",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "avg_over_time(airgradient_nox_raw[2m])"
    }
   ]
  },
  {
   "title": "VOC Raw",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "avg_over_time(airgradient_tvoc_raw[2m])",
     "legendFormat": "VOC Raw"
    }
   ]
  }
 ]
}